# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e80caf691105273a7b42f2959e993cb21be393cd108dfdf8c530e2faf7a7be6ea530a9eed9df2c2b972c5eef77fd84deece8ddd1df44208acbbaacd7e18e018d

test:
  secret_key_base: 2f1650d6fe9688b6d92e7f8196bb4689c981f73ef49ce20f43b852ed9587a964c3b042513db26d78de11b487a6161e0c896944bc64c0654d3e05f95f556c892d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
